.TH BEAK 1
.SH NAME
beak \- a backup-mirror-share-rotation-pruning tool

.SH SYNOPSIS
.B beak
[\fB\-i\fR \fIPATTERN\fR]
[\fB\-x\fR \fIPATTERN\fR]
[\fB\-p\fR \fIDEPTH\fR]
[\fB\-ta\fR \fISIZE\fR]
[\fB\-tr\fR \fISIZE\fR]
[\fB\-tx\fR \fIPATTERN\fR]
[\fB\--log=<tags>\fR
[\fB\-d\fR|\fB\--debug\fR]
[\fB\-v\fR|\fB\--verbose\fR]
[\fB\-V\fR|\fB\--version\fR]
[\fB\-h\fR]
\fI<args>\fR

.SH DESCRIPTION
.B beak

Example:    % beak push /home/you/Work /media/you/USBDrive

.SH OPTIONS
.TP
.BR \-i " " PATTERN
Only include files and directories with paths that match the pattern.

.TP
.BR \-x " " PATTERN
Exclude files and directories with paths that match the pattern.

.TP
.BR \-p " " DEPTH
Trigger tar generation at this depth, even if the trigger size has not been reached.
The default is 2, aka the first subdirectory level below the source directory.

.TP
.BR \-ta " " SIZE
Set the target tar size.

.TP
.BR \-tr " " SIZE
Set the tar trigger size.

.TP
.BR \-tx " " PATTERN
Trigger tar generation when the path of the directory matches the pattern.

.TP
.BR \-f
Run in foreground, ie do not start daemon.

.TP
.BR \-d
Run in debug mode foreground, a lot of output.

.SH EXAMPLES
.TP

Store all all virtual tar files in the source directory, ie no subdirectories.

% beak store -p 0 -ta 50M -tr 1T /home/you/Work WorkArchive

.TP
Tar the dev directory but exclude file/paths that contains the text "shm". Which are the share memory buffers, not suitable for archiving.

% beak mount -x shm /dev Test

.SH AUTHOR
Written by Fredrik Öhrström.

.SH COPYRIGHT
Copyright \(co 2016-2017 Fredrik Öhrström.
.br
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
