
Archive:
7z
apk
arj
deb
gz
tar.gz
tgz
pkg
rar
rpm
xz
z
zip

Config:
yml
cfg
conf

Data:
csv
dat
log
xml

DiskImage:
iso
dmg

Document:
doc  # ms word
docx # ms word
odt  # openoffice/libreoffice text
ods  # openoffice/libreoffice spreadsheet
pdf  # portable document format
ps   # postscript
rtf  # ms rich text format
tex
txt
wks  # ms works
wpd  # ms works
wps  # word perfect document
xls  # ms excel
xlsx # ms excel

Executable:
com
exe
jar


Image:
ai
bmp
gif
ico
jpg
jpeg
png
psd
svg
tif
tiff


Source:
c
h
cc
cs
js
pl
py
sh
vb
asm
bat
cpp
hpp
sql
java
swift
makefile


Object:
o
class


Sound:
aif
cda
mid
midi
mp3
mpa
ogg
wav
wma
flac


Video:
avi
flv
h264
m4v
mkv
mov
mp4
mpg
mpeg
webm
wmv

Web:
css
html
