
Archive:
7z
apk
arj
deb
gz
tar.gz
tgz
pkg
rar
rpm
xz
z
zip

Config:
yml
cfg
conf

Data:
csv
dat
json
log
xml

DiskImage:
iso
dmg
vhd  # virtual hard disk ms
vmdk # virtual machine disk vmware
dsk  # virtual machine disk vmware
vdi  # virtual disk image virtualbox
qcow # qemu disk image
qcow2 # qemu disk image

Document:
doc  # ms word
docx # ms word
odt  # openoffice/libreoffice text
ods  # openoffice/libreoffice spreadsheet
pdf  # portable document format
ps   # postscript
rtf  # ms rich text format
key  # keynote presentation
pps
ppt
tex
txt
wks  # ms works
wpd  # ms works
wps  # word perfect document
xls  # ms excel
xlsx # ms excel

Executable:
com
exe
jar


Image:
ai
bmp
gif
ico
jpg
jpeg
png
psd
svg
tif
tiff
tga
xcf


Source:
c
h
m
cc
cs
js
pl
py
sh
vb
asm
bas
bat
cpp
dtd
hpp
sql
java
swift
makefile
vcxproj
xcodeproj

Object:
o
class


Audio:
aif
cda
mid
midi
mp3
mpa
ogg
wav
wma
flac


Video:
avi
flv
h264
m4v
mkv
mov
mp4
mpg
mpeg
webm
wmv

Web:
css
htm
html
