name: Build MacOS
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - id: INSTALL_MACFUSE
      run: brew install --cask macfuse
    - id: INSTALL_ADDITIONAL_BUILD_DEPENDENCIES
      run: brew install bash findutils coreutils rsync libgphoto2 librsync openssl imagemagick ffmpeg exiv2 gawk gnu-sed gnu-tar
    - id: CONFIGURE
      run: ./configure --disable-fuse
    - id: CHECK
      run: find build -name "libfuse*"
    - id: CAT
      run: cat build/arm-apple-darwin23.5.0/spec.mk
    - id: MAKE
      run: make VERBOSE=
    - id: TEST
      run: make test
