name: Build MacOSX
on:
  push:
    branches:
      - master
      - AddMacOSX

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - id: INSTALL_ADDITIONAL_BUILD_DEPENDENCIES
      run: brew install fuse openssl
    - id: CONFIGURE
      run: ./configure --with-openssl=/usr/local/opt/openssl
    - id: MAKE
      run: make VERBOSE=
    - id: TEST
      run: make test
