name: Build MacOS
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - id: INSTALL_ADDITIONAL_BUILD_DEPENDENCIES
      run: brew install openssl imagemagick ffmpeg exiv2
    - id: CONFIGURE
      run: ./configure --with-openssl=/usr/local/Cellar/openssl@3/3.1.0 --disable-fuse
    - id: CHECK
      run: find /usr/local -name sha.h
    - id: CAT
      run: cat build/x86_64-apple-darwin*/spec.gmk
    - id: MAKE
      run: make VERBOSE=
    - id: TEST
      run: make test
